# Generated by Django 5.1.3 on 2024-11-05 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_name_service_title_remove_service_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['reminder_date'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(help_text='Enter the date and time of the appointment', verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(help_text='Select the client for the appointment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indicates if the appointment is completed', verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, help_text='Enter the reservation fee for the appointment', max_digits=10, verbose_name='Reservation Fee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reserved',
            field=models.BooleanField(default=False, help_text='Indicates if the appointment is reserved', verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Select the service for the appointment', on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount of the payment', max_digits=10, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(help_text='Select the appointment for the payment', on_delete=django.db.models.deletion.CASCADE, to='services.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Indicates if the payment is the final payment', verbose_name='Is Final'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_reservation',
            field=models.BooleanField(default=False, help_text='Indicates if the payment is for a reservation', verbose_name='Is Reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when the payment was made', verbose_name='Payment Timestamp'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='appointment',
            field=models.ForeignKey(help_text='Select the appointment for the reminder', on_delete=django.db.models.deletion.CASCADE, to='services.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateTimeField(help_text='Enter the date and time for the reminder', verbose_name='Reminder Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Enter a detailed description of the service', verbose_name='Service Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the service', null=True, upload_to='service_images/', verbose_name='Service Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the price of the service', max_digits=10, verbose_name='Service Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Enter the title of the service', max_length=100, verbose_name='Service Title'),
        ),
    ]
